<?
$fecha_hoy = date('Y')."/".date('m')."/".date('d');
			 $idx = $_POST['codigo'];
			 $rolx = $_POST['rol'];
			 $direx = $_POST['dire'];
			 $viax = $_POST['via'];
			 $numx = $_POST['num'];
			 $blockx = $_POST['block'];
			 $deptox = $_POST['depto'];
			 $sitiox = $_POST['sitio'];
			 $manx = $_POST['man'];
			 $pobx = $_POST['pob'];
			 $refx = $_POST['referencia'];
			 $zonax = $_POST['zona'];
			 $urbax = $_POST['urba'];
			 $tipox = $_POST['tipo'];
			 $usox = $_POST['uso'];
			 $expox = $_POST['expo'];
			 $radiox = $_POST['radio'];
			 $classx = $_POST['class'];
			 $mtx = $_POST['mt'];
			 $mtcx = $_POST['mtc'];
			 $kx = $_POST['kardex'];
			 $folioz=$_POST['foliox'];
			 
			 $girox = $_POST['giro'];
			 $orden = $_POST['orden'];
			 $fechg = $_POST['fechagiro'];
			 
			  $n1x = $_POST["via1"];
			  $n2x = $_POST["via2"];
			  $n3x = $_POST["via3"];
			  $n4x = $_POST["via4"];
			  $a1x = $_POST["ante1"];
			  $a2x = $_POST["ante2"];
			  $a3x = $_POST["ante3"];
			  $a4x = $_POST["ante4"];
			  $l1x = $_POST["linea1"];
			  $l2x = $_POST["linea2"];
			  $l3x = $_POST["linea3"];
			  $l4x = $_POST["linea4"];
			  $d1x = $_POST["derecho1"];
			  $d2x = $_POST["derecho2"];
			  $d3x = $_POST["derecho3"];
			  $d4x = $_POST["derecho4"];
	 		  $pcx = $_POST["pc"];
			  $pcdx = $_POST["pcd"];
			  $rfx = $_POST["rf"];
			  $rfdx = $_POST["rfd"];
			  $oax = $_POST["antece"];
			  
 			  $sitpatx = $_POST["sitpatente"];
			  $obspatx = $_POST["obspat"];
			  $numnx = $_POST["numnuevo"];
			  $obsx = $_POST["FCKeditor2"];			  
		 	  $link=conectarse();
    	      $sql= "UPDATE propiedades SET
			 tipocalle='$viax',
			 direccion='$direx',
			 numero='$numx',
			 depto='$deptox',
			 block='$blockx',
			 pob='$pobx',
			 manzana='$manx',
			 sitio='$sitiox',
			 clase='$classx',
			 tipo='$tipox',
			 mt2total='$mtx',
			 mt2cons='$mtcx',
			 uso='$usox',
			 nombre_referencial='$refx',
			 urbanizacion='$urbax',
			 kardex='$kx',
			 expropiacion='$expox',
			 radiourbano='$radiox',
			 obs='$obsx',
 			 n1='$n1x',
			 n2='$n2x',
			 n3='$n3x',
			 n4='$n4x',
			 a1='$a1x',
			 a2='$a2x',
			 a3='$a3x',
			 a4='$a4x',
			 l1='$l1x',
			 l2='$l2x',
			 l3='$l3x',
			 l4='$l4x',
			 d1='$d1x',
			 d2='$d2x',
			 d3='$d3x',
			 d4='$d4x',
			 pc='$pcx',
			 pcdate='$pcdx',
			 rf='$rfx',
			 rfdate='$rfdx',
			 estadopatente='$sitpatx',
			 festadopatente='$fecha_hoy',
			 otrosnum='$numnx',
			 obspatente='$obspatx',
			 oa='$oax',			 
			 zona='$zonax' WHERE id='$idx'";
   		     $result2=mysql_query($sql);
  		     mysql_close($link);
?>